#!/usr/bin/env python
"""Entry point for XBPM GUI application."""

import sys
from PyQt5.QtWidgets import QApplication
from xbpm_bumps.ui.main_window import XBPMMainWindow


def main():
    """Launch the XBPM GUI application."""
    app = QApplication(sys.argv)
    app.setApplicationName("XBPM Analysis")
    app.setOrganizationName("LNLS")
    
    window = XBPMMainWindow()
    window.show()
    
    sys.exit(app.exec_())


if __name__ == '__main__':
    main()
